#!/usr/bin/env python3
"""
WN-DDNM: Wavelet-based Null-space Denoising Diffusion Model

Key Innovation:
- Wavelet-based Low-Pass Filter (LPF) as degradation operator A
- Range-Null space decomposition for speckle removal:
  - Range-space: A†·A·y_obs (preserved low-frequency tissue structure)
  - Null-space: (I - A†A)·x̂_0|t (high-frequency regenerated by diffusion prior)

Algorithm (Linear Space):
1. y_obs = normalize(input)  # Work in [0, 1] linear space
2. Pre-compute range-space: A†·A·y_obs (low-frequency tissue)
3. For each timestep t in reverse diffusion:
   - Predict x̂_0|t from model
   - Null-space: (I - A†A)·x̂_0|t (high-frequency from diffusion)
   - Combine: x̄_0|t = Range(observation) + Null(prediction)
   - DDIM step: x_{t-1} = update(x̄_0|t)

Advantages:
- Clear separation: Range-space (tissue) / Null-space (speckle)
- Diffusion prior generates natural high-frequency instead of noise
- Works in linear space matching diffusion model training
- No log/exp transform instability issues
"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
import paths  # registers code subdirs on sys.path


import os
import torch
import torch.nn.functional as F
import numpy as np
from PIL import Image
import argparse
import atexit
import json
import warnings
from tqdm import tqdm
import matplotlib.pyplot as plt
import pywt
import yaml
from scipy.ndimage import gaussian_filter

from guided_diffusion.unet import UNetModel
from evaluation.metrics_core import gcnr as core_gcnr
from evaluation.metrics_core import snr as core_snr


PRESET_FILES = {
    'paper': paths.CONFIG_DIR / 'ugns_paper.yaml',
    'paper-repro': paths.CONFIG_DIR / 'paper_repro.yaml',
}


def load_preset_defaults(preset_name):
    """Load CLI defaults for a named inference preset."""
    preset_path = PRESET_FILES[preset_name]
    with preset_path.open('r', encoding='utf-8') as handle:
        values = yaml.safe_load(handle) or {}
    if not isinstance(values, dict):
        raise ValueError(f"Preset must contain a YAML mapping: {preset_path}")
    return values


def configure_cuda_runtime(device, batch_size):
    """Warn about small GPUs and arrange end-of-run peak-memory reporting."""
    requested = torch.device(device)
    if requested.type != 'cuda' or not torch.cuda.is_available():
        return

    device_index = requested.index
    if device_index is None:
        device_index = torch.cuda.current_device()
    properties = torch.cuda.get_device_properties(device_index)
    if properties.total_memory < 10 * 1024 ** 3:
        warnings.warn(
            "The selected GPU has less than 10 GiB of VRAM. Try --batch_size 5 "
            "or --batch_size 2 if allocation fails; changing batch_size changes "
            "the sampled ensemble because UGNS seeds each chunk separately.",
            RuntimeWarning,
        )

    torch.cuda.reset_peak_memory_stats(device_index)

    def _report_peak_memory():
        peak_gib = torch.cuda.max_memory_allocated(device_index) / (1024 ** 3)
        print(f"Peak CUDA memory allocated: {peak_gib:.3f} GiB")

    atexit.register(_report_peak_memory)


# ============================================================
# Low-Pass Filter Operator Class
# ============================================================

class LowPassFilterOperator:
    """
    Low-Pass Filter as DDNM degradation operator A

    For WN-DDNM, we define:
    - A: Low-pass filter (extracts low-frequency)
    - A†: Adjoint/pseudo-inverse (same as A for symmetric LPF)
    - Range-space: A†·A (low-frequency subspace)
    - Null-space: I - A†·A (high-frequency subspace)

    Supports two modes:
    1. 'avgpool': AvgPool2d + Upsample (spatial domain)
    2. 'wavelet': DWT LL sub-band extraction (wavelet domain)

    Wavelet mode is preferred for ultrasound as it provides:
    - Multi-scale decomposition
    - Natural tissue-speckle separation
    """

    def __init__(
        self,
        mode='wavelet',
        kernel_size=4,
        wavelet='sym4',
        level=3,
        srad_iterations=15,
        srad_q0=0.4,
        srad_delta_t=0.25,
    ):
        """
        Args:
            mode: 'wavelet' or 'avgpool'
            kernel_size: Kernel size for avgpool mode
            wavelet: Wavelet family for wavelet mode
            level: Decomposition level for wavelet mode
        """
        self.mode = mode
        self.kernel_size = kernel_size
        self.wavelet = wavelet
        self.level = level
        self.srad_iterations = srad_iterations
        self.srad_q0 = srad_q0
        self.srad_delta_t = srad_delta_t

        print(f"\n{'='*60}")
        print(f"LowPassFilterOperator Initialized")
        print(f"{'='*60}")
        print(f"Mode: {mode}")
        if mode == 'avgpool':
            print(f"Kernel size: {kernel_size}")
        else:
            print(f"Wavelet: {wavelet}, Level: {level}")
        print(f"{'='*60}\n")

    def forward(self, x):
        """
        A: Apply low-pass filter

        Args:
            x: Input image (2D numpy array)
        Returns:
            Low-pass filtered image (same size as input)
        """
        if self.mode == 'avgpool':
            return self._avgpool_forward(x)
        else:
            return self._wavelet_forward(x)

    def _avgpool_forward(self, x):
        """AvgPool + Upsample implementation"""
        k = self.kernel_size
        H, W = x.shape

        # Pad to make divisible by kernel size
        pad_h = (k - H % k) % k
        pad_w = (k - W % k) % k
        if pad_h > 0 or pad_w > 0:
            x_padded = np.pad(x, ((0, pad_h), (0, pad_w)), mode='reflect')
        else:
            x_padded = x

        # Convert to tensor for pooling
        x_tensor = torch.from_numpy(x_padded).float().unsqueeze(0).unsqueeze(0)

        # AvgPool
        pooled = F.avg_pool2d(x_tensor, k, k)

        # Upsample back to original size
        upsampled = F.interpolate(pooled, size=x_padded.shape, mode='bilinear', align_corners=False)

        # Crop to original size
        result = upsampled.squeeze().numpy()[:H, :W]

        return result

    def _wavelet_forward(self, x):
        """
        Wavelet LL sub-band extraction

        This extracts only the low-frequency (LL) component and reconstructs,
        effectively zeroing out all high-frequency detail coefficients.
        """
        # Multi-level decomposition
        coeffs = pywt.wavedec2(x, self.wavelet, level=self.level, mode='symmetric')

        # Keep only approximation, zero out all details
        coeffs_lpf = [coeffs[0]]  # LL approximation
        for i in range(1, len(coeffs)):
            cH, cV, cD = coeffs[i]
            coeffs_lpf.append((np.zeros_like(cH), np.zeros_like(cV), np.zeros_like(cD)))

        # Reconstruct
        result = pywt.waverec2(coeffs_lpf, self.wavelet, mode='symmetric')

        # Handle size mismatch due to wavelet padding
        result = result[:x.shape[0], :x.shape[1]]

        return result

    def srad_filter(self, x, num_iter=None, q0=None, delta_t=None):
        """Speckle-Reducing Anisotropic Diffusion (SRAD) filter."""
        iterations = self.srad_iterations if num_iter is None else num_iter
        q0_val = self.srad_q0 if q0 is None else q0
        dt = self.srad_delta_t if delta_t is None else delta_t
        dt = np.clip(dt, 1e-4, 0.25)

        img = x.astype(np.float32)
        eps = 1e-12

        for _ in range(max(1, iterations)):
            padded = np.pad(img, 1, mode='edge')
            c = padded[1:-1, 1:-1]
            n = padded[:-2, 1:-1]
            s = padded[2:, 1:-1]
            e = padded[1:-1, 2:]
            w = padded[1:-1, :-2]

            dN = n - c
            dS = s - c
            dE = e - c
            dW = w - c

            c_sq = c * c + eps
            grad_sq = (dN ** 2 + dS ** 2 + dE ** 2 + dW ** 2) / c_sq
            laplace = (dN + dS + dE + dW) / (c + eps)

            denom = (1.0 + 0.25 * laplace)
            q_sq = (0.5 * grad_sq - 0.25 * laplace ** 2) / (denom * denom + eps)

            if q0_val is None or q0_val <= 0:
                q0_sq = float(np.mean(q_sq))
            else:
                q0_sq = float(q0_val * q0_val)

            q0_sq = max(q0_sq, eps)
            c_coef = 1.0 / (1.0 + (q_sq - q0_sq) / (q0_sq * (1.0 + q0_sq) + eps))
            c_coef = np.clip(c_coef, 0.0, 1.0)

            img = c + (dt / 4.0) * (c_coef * dN + c_coef * dS + c_coef * dE + c_coef * dW)

        return np.clip(img, 0.0, 1.0)

    def adjoint(self, y):
        """
        A†: Adjoint operator

        For symmetric LPF, the adjoint is the same as forward.
        This is because LPF is a projection operator.
        """
        return self.forward(y)

    def range_space_projection(self, x):
        """
        A†·A·x: Project onto range-space (observed low-frequency)

        Implemented explicitly as A†(A(x)) to match the DDNM formulation.
        For symmetric LPF, A† = A and A is idempotent, so A†A ≈ A.

        """
        # Explicit A†A structure (even if A is symmetric)
        return self.adjoint(self.forward(x))

    def null_space_projection(self, x):
        """
        (I - A†A)·x: Project onto null-space (unobserved high-frequency)

        This extracts the high-frequency components that are
        NOT captured by the low-pass filter.

        """
        return x - self.range_space_projection(x)

    def forward_torch(self, x):
        """Torch version of forward for batch processing"""
        if self.mode == 'avgpool':
            k = self.kernel_size
            # x: (B, 1, H, W)
            pooled = F.avg_pool2d(x, k, k)
            upsampled = F.interpolate(pooled, size=x.shape[-2:], mode='bilinear', align_corners=False)
            return upsampled
        else:
            # Wavelet mode - process each sample in batch
            B, C, H, W = x.shape
            results = []
            for b in range(B):
                x_np = x[b, 0].cpu().numpy()
                result = self._wavelet_forward(x_np)
                results.append(result)
            return torch.from_numpy(np.stack(results)).unsqueeze(1).float().to(x.device)





# ============================================================
# Diffusion Utilities
# ============================================================

def get_beta_schedule(beta_schedule, beta_start, beta_end, num_timesteps):
    """Get beta schedule for diffusion"""
    if beta_schedule == "linear":
        return np.linspace(beta_start, beta_end, num_timesteps, dtype=np.float64)
    else:
        raise NotImplementedError(f"Unknown beta schedule: {beta_schedule}")


# ============================================================
# WN-DDNM Denoiser Class
# ============================================================

class WNDDNMDenoiser:
    """
    WN-DDNM: Wavelet-based Null-space Denoising Diffusion Model

    Works in LINEAR space [0, 1] for stability:
    1. Range-Null decomposition with LPF operator during reverse diffusion
    2. Range-space preserves low-frequency tissue structure from observation
    3. Null-space regenerates high-frequency from diffusion prior

    The core insight:
    - Range-space (A†·A·y_obs): Preserves observed low-frequency tissue structure
    - Null-space ((I-A†A)·x̂_0|t): Regenerates high-frequency from diffusion prior
    - Since speckle is high-frequency, it gets replaced by clean samples!

    Uses DDIM-style updates because Range-Null decomposition modifies x0_pred
    at each step. The modified x0_hat must be used in the diffusion update.
    """

    def __init__(
        self,
        checkpoint_path,
        config_path,
        device='cuda',
        ensemble_size=10,
        batch_size=10,
        ddim_steps=100,
        guidance_start=0.3,
        guidance_end=0.0,
        guidance_power=2.0,
        lpf_mode='wavelet',
        lpf_kernel_size=3,
        lpf_wavelet='sym4',
        lpf_level=3,
        range_weight=1.0,
        null_weight=1.0,
        timestep_schedule='karras',
        eta=0.0,
        guidance_schedule='cosine',
        use_linear_range=True,
        db_range=60,
        use_otsu_gate=True,
        sampler='ddim',
        linear_mask_center=0.4,
        linear_mask_steepness=3.5,
        max_intensity_cap=0.92,
        otsu_strength=0.7,
        use_wavelet=True,
        use_srad=True,
        srad_iterations=15,
        srad_q0=0.4,
        srad_delta_t=0.25,
        use_best_sample_fusion=True,
        fusion_strategy='paper',
        fusion_w_min=0.7,
        fusion_w_max=0.98,
        topk=5,
        fusion_temperature=0.3,
    ):
        """
        Args:
            checkpoint_path: Path to model checkpoint
            config_path: Path to config JSON
            device: 'cuda' or 'cpu'
            ensemble_size: Number of samples for ensemble averaging
            batch_size: Batch size for parallel processing
            ddim_steps: Number of sampling steps
            guidance_start: Initial guidance strength
            guidance_end: Final guidance strength
            guidance_power: Guidance decay curve exponent
            lpf_mode: 'wavelet' or 'avgpool' for LPF operator
            lpf_kernel_size: Kernel size for avgpool mode
            lpf_wavelet: Wavelet family for wavelet mode
            lpf_level: Decomposition level for wavelet mode
            range_weight: Weight for range-space preservation (default 1.0)
            null_weight: Weight for null-space regeneration (default 1.0)
            timestep_schedule: Timestep spacing ('uniform', 'karras', 'exponential', 'quadratic')
            eta: DDIM stochasticity (0=deterministic, 1=DDPM-like)
            guidance_schedule: Guidance decay schedule ('power', 'cosine', 'linear')
            sampler: Sampler type ('ddim' only)
            use_otsu_gate: Enable Otsu-based soft background gate for linear mask
            max_intensity_cap: Upper bound for intensity mask to reduce white saturation
            otsu_strength: Otsu gate blending strength (0=off, 1=full)
            use_wavelet: Enable wavelet/LPF projection for range space
            use_srad: Enable SRAD pre-filtering for range projection
            srad_iterations: SRAD iterations
            srad_q0: SRAD q0 parameter (<=0 uses auto estimate)
            srad_delta_t: SRAD time step (0 < dt <= 0.25)
            use_best_sample_fusion: Enable best-sample-aware fusion
            fusion_strategy: 'paper', 'frequency', 'uncertainty_blend', or 'topk'
            fusion_w_min: Minimum ensemble-mean weight for paper fusion
            fusion_w_max: Maximum ensemble-mean weight for paper fusion
            topk: Number of samples for top-k weighted fusion
            fusion_temperature: Softmax temperature for quality weighting
        """
        self.device = device
        self.C = ensemble_size
        self.batch_size = batch_size if batch_size is not None else ensemble_size
        self.ddim_steps = ddim_steps
        self.guidance_start = guidance_start
        self.guidance_end = guidance_end
        self.guidance_power = guidance_power
        self.range_weight = range_weight
        self.null_weight = null_weight
        self.timestep_schedule = timestep_schedule
        self.eta = eta
        self.guidance_schedule = guidance_schedule
        self.use_linear_range = use_linear_range
        self.db_range = db_range
        self.use_otsu_gate = use_otsu_gate
        self.sampler = sampler
        self.linear_mask_center = linear_mask_center
        self.linear_mask_steepness = linear_mask_steepness
        self.max_intensity_cap = float(np.clip(max_intensity_cap, 0.0, 1.0))
        self.otsu_strength = float(np.clip(otsu_strength, 0.0, 1.0))
        self.use_wavelet = use_wavelet
        self.use_srad = use_srad
        self.srad_iterations = srad_iterations
        self.srad_q0 = srad_q0
        self.srad_delta_t = srad_delta_t
        self.use_best_sample_fusion = use_best_sample_fusion
        self.fusion_strategy = fusion_strategy
        self.fusion_w_min = float(fusion_w_min)
        self.fusion_w_max = float(fusion_w_max)
        if not 0.0 <= self.fusion_w_min <= self.fusion_w_max <= 1.0:
            raise ValueError("fusion weights must satisfy 0 <= w_min <= w_max <= 1")
        self.topk = max(1, int(topk))
        self.fusion_temperature = max(1e-3, float(fusion_temperature))
        # Initialized for adaptive range-null fusion.
        self._intensity_mask = None
        self._intensity_weight = None
        self._weight_mask = None
        self._use_adaptive_mask = False
        self._warned_gamma_cap = False
        self._bright_iso_np = None

        valid_fusion_strategies = {'paper', 'frequency', 'uncertainty_blend', 'topk'}
        if self.fusion_strategy not in valid_fusion_strategies:
            raise ValueError(
                f"Unknown fusion_strategy: {self.fusion_strategy}. "
                f"Choose from {sorted(valid_fusion_strategies)}."
            )

        # Load config
        with open(config_path, 'r') as f:
            self.config = json.load(f)
        self.model_size_multiple = self._infer_model_size_multiple()
        self._last_input_original = None
        self._last_input_shape = None
        self._last_model_shape = None
        self._last_input_padding = (0, 0)

        # Setup diffusion
        self.num_timesteps = self.config['diffusion_steps']
        self._setup_diffusion_schedule()

        # Load model
        self.model = self._load_model(checkpoint_path)

        # Setup timesteps
        self._setup_timesteps()

        # Initialize LPF operator (for mask computation: full level)
        self.lpf = LowPassFilterOperator(
            mode=lpf_mode,
            kernel_size=lpf_kernel_size,
            wavelet=lpf_wavelet,
            level=lpf_level,
            srad_iterations=self.srad_iterations,
            srad_q0=self.srad_q0,
            srad_delta_t=self.srad_delta_t,
        )
        # Separate LPF for range projection (reduced level/srad → less PSF blurring → better FWHM)
        _range_level = max(1, lpf_level // 2)
        _range_srad = min(5, self.srad_iterations)
        self.lpf_range = LowPassFilterOperator(
            mode=lpf_mode,
            kernel_size=lpf_kernel_size,
            wavelet=lpf_wavelet,
            level=_range_level,
            srad_iterations=_range_srad,
            srad_q0=self.srad_q0,
            srad_delta_t=self.srad_delta_t,
        )

        print(f"\n{'='*60}")
        print(f"WN-DDNM Denoiser Initialized")
        print(f"{'='*60}")
        print(f"Sampler: {self.sampler.upper()}")
        print(f"Timestep schedule: {self.timestep_schedule}")
        print(f"Eta (stochasticity): {self.eta}")
        print(f"Model size multiple: {self.model_size_multiple}")
        print(f"Ensemble size: {self.C} (batch_size={self.batch_size})")
        print(f"Sampling steps: {self.ddim_steps}")
        print(f"Guidance: λ(t) from {self.guidance_start} to {self.guidance_end} ({self.guidance_schedule})")
        print("Intensity domain: linear")
        print(f"LPF mode: {lpf_mode}")
        print(f"Wavelet LPF enabled: {self.use_wavelet}")
        print(f"SRAD enabled: {self.use_srad}")
        if self.use_srad:
            print(f"  SRAD: iter={self.srad_iterations}, q0={self.srad_q0}, dt={self.srad_delta_t}")
        print(f"Best-sample fusion enabled: {self.use_best_sample_fusion}")
        if self.use_best_sample_fusion:
            print(
                f"  Strategy: {self.fusion_strategy} "
                f"(topk={self.topk}, temp={self.fusion_temperature:.3f})"
            )
        print(f"Range weight: {self.range_weight}, Null weight: {self.null_weight}")
        print(
            f"Adaptive mask: c={self.linear_mask_center}, "
            f"gamma={self.linear_mask_steepness}, D={self.db_range} dB"
        )
        if self.use_linear_range:
            print(f"Range-space: Linear domain (B-mode → Linear, db_range={self.db_range})")
        else:
            print(f"Range-space: B-mode domain (original)")
        print(f"{'='*60}\n")

    def _setup_diffusion_schedule(self):
        """Setup beta/alpha schedules"""
        betas = get_beta_schedule(
            self.config['noise_schedule'],
            0.0001,
            0.02,
            self.num_timesteps
        )
        self.betas = torch.from_numpy(betas).float().to(self.device)

        alphas = 1.0 - self.betas
        self.alphas_cumprod = torch.cumprod(alphas, dim=0)
        self.alphas_cumprod_prev = torch.cat([
            torch.ones(1).to(self.device),
            self.alphas_cumprod[:-1]
        ])

        self.sqrt_alphas_cumprod = torch.sqrt(self.alphas_cumprod)
        self.sqrt_one_minus_alphas_cumprod = torch.sqrt(1.0 - self.alphas_cumprod)
        self.sqrt_recip_alphas_cumprod = torch.sqrt(1.0 / self.alphas_cumprod)
        self.sqrt_recipm1_alphas_cumprod = torch.sqrt(1.0 / self.alphas_cumprod - 1)

    def _setup_timesteps(self):
        """Setup subsampled timesteps with various scheduling options

        Supported schedules:
        - 'uniform': Standard uniform spacing (default)
        - 'karras': Karras et al. schedule (better quality at low steps)
        - 'exponential': Exponential spacing (large steps early, small late)
        - 'quadratic': Quadratic spacing

        Note: All schedules use DDIM-style updates with WN-DDNM range-null decomposition.
        """
        n = self.ddim_steps
        T = self.num_timesteps

        if self.timestep_schedule == 'uniform':
            # Standard uniform spacing
            step = T // n
            self.ddim_timesteps = list(range(0, T, step))[::-1]

        elif self.timestep_schedule == 'karras':
            # Karras et al. schedule: σ_i = (σ_max^(1/ρ) + i/(n-1) * (σ_min^(1/ρ) - σ_max^(1/ρ)))^ρ
            # Convert sigma to timesteps via alpha_bar relationship
            rho = 7.0
            sigma_min = 0.002
            sigma_max = 80.0

            ramp = np.linspace(0, 1, n)
            min_inv_rho = sigma_min ** (1 / rho)
            max_inv_rho = sigma_max ** (1 / rho)
            sigmas = (max_inv_rho + ramp * (min_inv_rho - max_inv_rho)) ** rho

            # Convert sigmas to timesteps: sigma = sqrt((1-alpha_bar)/alpha_bar)
            # So alpha_bar = 1 / (1 + sigma^2)
            alpha_bars = 1.0 / (1.0 + sigmas ** 2)

            # Find closest timesteps
            alphas_np = self.alphas_cumprod.cpu().numpy()
            timesteps = []
            for ab in alpha_bars:
                t = np.argmin(np.abs(alphas_np - ab))
                timesteps.append(int(t))

            # Remove duplicates while preserving order, then reverse for T -> 0
            seen = set()
            unique_timesteps = []
            for t in timesteps:
                if t not in seen:
                    seen.add(t)
                    unique_timesteps.append(t)
            self.ddim_timesteps = unique_timesteps

        elif self.timestep_schedule == 'exponential':
            # Exponential spacing: more steps near t=0 (fine details)
            # t_i = T * exp(-k * i/n), where k controls steepness
            k = 3.0  # Steepness factor
            ramp = np.linspace(0, 1, n)
            timesteps = T * np.exp(-k * ramp)
            timesteps = np.clip(timesteps, 0, T - 1).astype(int)

            # Remove duplicates and reverse
            seen = set()
            unique_timesteps = []
            for t in timesteps:
                if t not in seen:
                    seen.add(t)
                    unique_timesteps.append(int(t))
            self.ddim_timesteps = unique_timesteps

        elif self.timestep_schedule == 'quadratic':
            # Quadratic spacing: t_i = T * (1 - (i/n)^2)
            ramp = np.linspace(0, 1, n)
            timesteps = T * (1 - ramp ** 2)
            timesteps = np.clip(timesteps, 0, T - 1).astype(int)

            # Remove duplicates
            seen = set()
            unique_timesteps = []
            for t in timesteps:
                if t not in seen:
                    seen.add(t)
                    unique_timesteps.append(int(t))
            self.ddim_timesteps = unique_timesteps

        else:
            raise ValueError(f"Unknown timestep_schedule: {self.timestep_schedule}")

        # Ensure we end at t=0 or close to it
        if self.ddim_timesteps[-1] > 0:
            self.ddim_timesteps.append(0)

    def _load_model(self, checkpoint_path):
        """Load trained diffusion model"""
        print(f"Loading model from: {checkpoint_path}")
        checkpoint = torch.load(checkpoint_path, map_location=self.device, weights_only=False)

        if 'args' in checkpoint:
            args = checkpoint['args']
        else:
            args = self.config

        in_channels = args.get('in_channels', 1)
        image_size = args.get('image_size', 256)
        num_channels = args.get('num_channels', 256)
        learn_sigma = args.get('learn_sigma', True)

        channel_mult = args.get('channel_mult', '')
        if isinstance(channel_mult, (list, tuple)):
            channel_mult = tuple(channel_mult)
        elif channel_mult == '':
            if image_size == 512:
                channel_mult = (0.5, 1, 1, 2, 2, 4, 4)
            elif image_size == 256:
                channel_mult = (1, 1, 2, 2, 4, 4)
            else:
                channel_mult = (1, 2, 3, 4)
        else:
            channel_mult = tuple(int(x) for x in channel_mult.split(','))

        attention_resolutions = args.get('attention_resolutions', '32,16,8')
        if isinstance(attention_resolutions, (list, tuple)):
            attention_ds = list(attention_resolutions)
        else:
            attention_ds = []
            for res in attention_resolutions.split(','):
                attention_ds.append(image_size // int(res))

        out_channels = in_channels * 2 if learn_sigma else in_channels

        model = UNetModel(
            image_size=image_size,
            in_channels=in_channels,
            model_channels=num_channels,
            out_channels=out_channels,
            num_res_blocks=args.get('num_res_blocks', 2),
            attention_resolutions=tuple(attention_ds),
            dropout=args.get('dropout', 0.0),
            channel_mult=channel_mult,
            num_classes=None,
            use_checkpoint=args.get('use_checkpoint', False),
            use_fp16=args.get('use_fp16', False),
            num_heads=args.get('num_heads', 4),
            num_head_channels=args.get('num_head_channels', 64),
            num_heads_upsample=args.get('num_heads_upsample', -1),
            use_scale_shift_norm=args.get('use_scale_shift_norm', True),
            resblock_updown=args.get('resblock_updown', True),
            use_new_attention_order=args.get('use_new_attention_order', False),
        ).to(self.device)

        if 'model_state_dict' in checkpoint:
            model.load_state_dict(checkpoint['model_state_dict'])
        else:
            model.load_state_dict(checkpoint)

        model.eval()
        print(f"Model loaded successfully!")

        return model

    def bmode_to_linear(self, bmode_01):
        """
        Invert B-mode [0,1] back to the linear envelope in [0,1].

        A B-mode image is log-compressed: B = 20*log10(L) + offset,
        so the inverse is L = 10^((B - offset) / 20).

        Args:
            bmode_01: B-mode image normalized to [0, 1]

        Returns:
            linear_01: Linear image normalized to [0, 1]
        """
        # B-mode [0,1] → dB scale [-db_range, 0]
        bmode_db = bmode_01 * self.db_range - self.db_range

        # dB → Linear: 10^(dB/20)
        linear = 10 ** (bmode_db / 20)

        # Clip negative values (shouldn't happen but safety)
        linear = np.clip(linear, 0, None)

        # Normalize to [0, 1]
        linear_01 = linear / (linear.max() + 1e-10)

        return linear_01

    def linear_to_bmode(self, linear_01):
        """
        Convert the linear envelope in [0,1] to B-mode in [0,1].

        B-mode = 20*log10(Linear), normalized to [0, 1].

        Args:
            linear_01: Linear image normalized to [0, 1]

        Returns:
            bmode_01: B-mode image normalized to [0, 1]
        """
        # Avoid log(0)
        linear_safe = np.clip(linear_01, 1e-10, None)

        # Linear → dB: 20*log10(L)
        bmode_db = 20 * np.log10(linear_safe)

        # dB scale: min ~ 0 → normalize to [0, 1]
        # bmode_db is in range [-inf, 0], clip to [-db_range, 0]
        bmode_db = np.clip(bmode_db, -self.db_range, 0)

        # Normalize: [-db_range, 0] → [0, 1]
        bmode_01 = (bmode_db + self.db_range) / self.db_range

        return bmode_01

    def compute_linear_intensity_mask(self, bmode_01_np):
        """
        Four-class intensity mask giving a per-pixel weight in [0, 1].

        Classes:
          1. Tissue:            bright + speckle texture (high local variance) -> mask high
          2. Anechoic:          very dark + low variance + darker than surroundings -> mask 0
          3. Background:        mid intensity, uniform speckle -> mask about 0.10
          4. Black background:  near zero (outside the scan cone, acoustic shadow) -> mask 0

        A global tissue detector suppresses the whole mask when the image contains
        no tissue, so a phantom holding only anechoic and background regions does
        not have tissue falsely detected in it.

        This replaces an earlier formulation and fixes four of its problems:
          - the Otsu gate is dropped; it was the root cause of background being
            classified as tissue in tissue-free images
          - the 0.15 texture-gate floor is dropped; forcing a 15% mask everywhere
            introduced background artifacts
          - the sigma=4 Gaussian is dropped to stop the mask bleeding into
            anechoic regions
          - a global scale is applied after min-max normalization so that absolute
            intensity context is preserved
        """
        def _avg_blur(x, k):
            if k <= 1:
                return x
            t = torch.from_numpy(x).unsqueeze(0).unsqueeze(0).float()
            t = F.avg_pool2d(t, k, stride=1, padding=k // 2)
            return t.squeeze().numpy()

        # ----------------------------------------------------------------
        # Step 1: B-mode -> linear conversion (true envelope values)
        # ----------------------------------------------------------------
        linear_01 = self.bmode_to_linear(bmode_01_np)

        # ----------------------------------------------------------------
        # Step 2: Optional SRAD + LPF smoothing
        # ----------------------------------------------------------------
        range_input = linear_01
        if self.use_srad:
            range_input = self.lpf.srad_filter(range_input)
        if self.use_wavelet:
            linear_smoothed = self.lpf.range_space_projection(range_input)
        else:
            linear_smoothed = range_input

        # ----------------------------------------------------------------
        # Step 3: normalize to [0, 1]
        # ----------------------------------------------------------------
        mask_min, mask_max = linear_smoothed.min(), linear_smoothed.max()
        if mask_max > mask_min:
            linear_norm = (linear_smoothed - mask_min) / (mask_max - mask_min)
        else:
            linear_norm = np.ones_like(linear_smoothed)

        # ----------------------------------------------------------------
        # Component A: Global tissue presence detector
        # Suppress the whole mask for images that hold no tissue (anechoic plus
        # background only). After min-max normalization even background speckle can
        # reach linear_norm close to 1.0, which would otherwise raise the mask on a
        # tissue-free image. Decide tissue presence globally from the raw B-mode
        # statistics instead.
        # ----------------------------------------------------------------
        b_raw = bmode_01_np.astype(np.float64)
        mu_a  = gaussian_filter(b_raw,       sigma=3.0, mode='reflect')
        mu_sq_a = gaussian_filter(b_raw ** 2, sigma=3.0, mode='reflect')
        local_std_a = np.sqrt(np.maximum(mu_sq_a - mu_a ** 2, 0.0)).astype(np.float32)

        # A1: bright-pixel fraction (tissue implies a larger share of top pixels)
        bright_fraction = float(np.mean(linear_norm > 0.60))
        # A2: intensity range (tissue + anechoic is wide; background only is narrow)
        intensity_range = float(
            np.percentile(linear_norm, 98) - np.percentile(linear_norm, 10)
        )
        # A3: mean local std over the brightest 20% -- high for tissue speckle, low for sidelobes
        bright_mask_a = linear_norm > float(np.percentile(linear_norm, 80))
        bright_std_mean = (
            float(np.mean(local_std_a[bright_mask_a]))
            if bright_mask_a.any() else 0.0
        )
        abs_std_thresh = 0.025  # minimum tissue-speckle std on the bmode_01 scale

        has_tissue = (
            (bright_fraction > 0.08 and intensity_range > 0.50)
            or (bright_fraction > 0.12)
            or (intensity_range > 0.62)
            or (bright_std_mean > abs_std_thresh and bright_fraction > 0.05)
        )

        if has_tissue:
            global_tissue_scale = 1.0
        else:
            # No tissue: soft suppression proportional to bright_fraction (max 0.25)
            global_tissue_scale = float(np.clip(bright_fraction / 0.08, 0.0, 1.0)) * 0.25

        print(f"  [Mask] tissue={has_tissue}, bright_frac={bright_fraction:.3f}, "
              f"range={intensity_range:.3f}, bright_std={bright_std_mean:.4f}, "
              f"global_scale={global_tissue_scale:.3f}")

        # ----------------------------------------------------------------
        # Component B: 4-class soft pixel classification
        # Separate background, anechoic, and tissue with an explicit four-class
        # sigmoid classification instead of an Otsu gate
        # ----------------------------------------------------------------
        # Reuse local_std computed in component A
        p95_std = float(np.percentile(local_std_a, 95))
        std_norm = np.clip(local_std_a / (p95_std + 1e-8), 0.0, 1.0)

        # Adaptive thresholds derived from image percentiles
        p5  = float(np.percentile(linear_norm, 5))
        p25 = float(np.percentile(linear_norm, 25))
        p50 = float(np.percentile(linear_norm, 50))

        # Class 4 - black background: near-zero pixels (outside the scan cone)
        black_thresh = max(p5, 0.02)
        black_bg_prob = (1.0 / (1.0 + np.exp(
            (linear_norm - black_thresh) / 0.015
        ))).astype(np.float32)

        # Class 3 - anechoic: dark, low variance, and darker than its surroundings.
        # Multiplying the three conditions leaves a high score only for true anechoic regions.
        local_mean_wide = gaussian_filter(
            linear_norm.astype(np.float64), sigma=8.0, mode='reflect'
        ).astype(np.float32)
        dark_contrast = np.clip(local_mean_wide - linear_norm, 0.0, None)
        anechoic_dark     = 1.0 / (1.0 + np.exp((linear_norm - p25) / 0.04))
        anechoic_low_var  = 1.0 / (1.0 + np.exp((std_norm - 0.18) / 0.04))
        anechoic_contrast = np.clip(dark_contrast / 0.08, 0.0, 1.0)
        anechoic_prob = (
            anechoic_dark * anechoic_low_var * anechoic_contrast
        ).astype(np.float32)
        anechoic_prob = anechoic_prob * (1.0 - black_bg_prob)

        # Class 1 - tissue: bright and carrying speckle texture
        tissue_int_thresh = max(p50, 0.35)
        tissue_bright   = 1.0 / (1.0 + np.exp(-(linear_norm - tissue_int_thresh) / 0.07))
        tissue_textured = 1.0 / (1.0 + np.exp(-(std_norm - 0.22) / 0.05))
        tissue_prob = (tissue_bright * tissue_textured).astype(np.float32)
        tissue_prob = tissue_prob * (1.0 - black_bg_prob)

        # Class 2 - background: the remainder (mid intensity, uniform speckle)
        background_prob = np.clip(
            1.0 - black_bg_prob - anechoic_prob - tissue_prob, 0.0, 1.0
        ).astype(np.float32)

        # ----------------------------------------------------------------
        # Component C: Adaptive mask assembly
        # ----------------------------------------------------------------
        # C1: tissue score -- apply the gamma mapping to the tissue class only
        gamma_raw = max(self.linear_mask_steepness, 1e-3)
        gamma = min(gamma_raw, 6.0)
        if gamma_raw > 6.0 and not self._warned_gamma_cap:
            print(f"WARNING: linear_mask_steepness={gamma_raw:.3f} > 6.0. Clamping to 6.0.")
            self._warned_gamma_cap = True

        denom = max(1e-10, 1.0 - self.linear_mask_center)
        tissue_norm = np.clip(
            (linear_norm - self.linear_mask_center) / denom, 0.0, 1.0
        )
        tissue_score = np.clip(tissue_norm ** gamma, 0.0, self.max_intensity_cap)
        tissue_score = tissue_score * 0.85 + 0.15 * np.tanh(tissue_score * 2.0)
        tissue_score = np.clip(tissue_score, 0.0, self.max_intensity_cap).astype(np.float32)

        # C2: combine the four class weights
        # - tissue:           gamma scoring
        # - anechoic:         0 (the diffusion prior cleans these regions on its own)
        # - background:       0.10 (a very low anchor that keeps a little spatial structure)
        # - black background: 0 (nothing to preserve)
        intensity_mask = (
            tissue_prob     * tissue_score +
            anechoic_prob   * 0.0 +
            background_prob * 0.10 +
            black_bg_prob   * 0.0
        ).astype(np.float32)
        intensity_mask = np.clip(intensity_mask, 0.0, 1.0)

        # C3: apply the global tissue scale (suppresses tissue-free images entirely)
        intensity_mask = intensity_mask * global_tissue_scale

        # C4: multi-scale smoothing (sigma=4 dropped; it was the main cause of anechoic bleed)
        mask_s1 = gaussian_filter(intensity_mask, sigma=1.0, mode='reflect')
        mask_s2 = gaussian_filter(intensity_mask, sigma=2.0, mode='reflect')
        intensity_mask = (0.65 * mask_s1 + 0.35 * mask_s2).astype(np.float32)
        intensity_mask = np.clip(intensity_mask, 0.0, 1.0)

        # C5: adaptive blur (bleed weight reduced from 0.4 to 0.25)
        h, w = intensity_mask.shape
        coverage = float(np.mean(intensity_mask > 0.3))
        k_max = int(round(min(h, w) / 16))
        k_max = max(11, min(31, k_max))
        if k_max % 2 == 0:
            k_max += 1
        k_min = 5
        coverage_norm = np.clip(coverage / 0.12, 0.0, 1.0)
        k = int(round(k_min + (1.0 - coverage_norm) * (k_max - k_min)))
        if k % 2 == 0:
            k += 1
        k = max(3, min(k, k_max))
        smooth = _avg_blur(intensity_mask, k)
        intensity_mask = (0.75 * intensity_mask + 0.25 * smooth).astype(np.float32)
        intensity_mask = np.clip(intensity_mask, 0.0, 1.0)

        # C6: Post-smoothing suppression
        # Push back down any mask value that smoothing bled into anechoic or black-background regions
        suppress_mask = np.clip(anechoic_prob + black_bg_prob, 0.0, 1.0)
        intensity_mask = intensity_mask * (1.0 - 0.85 * suppress_mask)
        intensity_mask = np.clip(intensity_mask, 0.0, 1.0)

        return intensity_mask

    def _range_projection_np(self, x_np):
        range_input = x_np
        if self.use_srad:
            range_input = self.lpf_range.srad_filter(range_input)
        if self.use_wavelet:
            return self.lpf_range.range_space_projection(range_input)
        return range_input

    def compute_guidance_strength(self, t):
        """Compute time-dependent guidance strength

        Supported schedules:
        - 'power': λ(t) = end + (start - end) * (t/T)^power (default)
        - 'cosine': λ(t) = end + (start - end) * (1 + cos(π*(1-t/T))) / 2
        - 'linear': λ(t) = end + (start - end) * (t/T)
        """
        t_normalized = t / self.num_timesteps

        if self.guidance_schedule == 'power':
            # Original power-based schedule
            lambda_t = self.guidance_end + (self.guidance_start - self.guidance_end) * (t_normalized ** self.guidance_power)

        elif self.guidance_schedule == 'cosine':
            # Cosine schedule: smoother transition
            lambda_t = self.guidance_end + (self.guidance_start - self.guidance_end) * \
                       (1 + np.cos(np.pi * (1 - t_normalized))) / 2

        elif self.guidance_schedule == 'linear':
            # Linear schedule
            lambda_t = self.guidance_end + (self.guidance_start - self.guidance_end) * t_normalized

        else:
            # Fallback to power
            lambda_t = self.guidance_end + (self.guidance_start - self.guidance_end) * (t_normalized ** self.guidance_power)

        return lambda_t

    def _infer_model_size_multiple(self):
        """Infer required spatial multiple from UNet depth."""
        channel_mult = self.config.get('channel_mult', '')
        if isinstance(channel_mult, str):
            levels = [c for c in channel_mult.split(',') if c.strip()]
            n_levels = len(levels)
        elif isinstance(channel_mult, (list, tuple)):
            n_levels = len(channel_mult)
        else:
            n_levels = 0
        if n_levels <= 1:
            return 32
        return int(2 ** (n_levels - 1))

    def _pad_to_model_compatible_size(self, img_np):
        """Pad 2D image to a model-compatible size using edge replication."""
        h, w = img_np.shape
        mult = max(2, int(self.model_size_multiple))
        pad_h = (mult - (h % mult)) % mult
        pad_w = (mult - (w % mult)) % mult
        if pad_h == 0 and pad_w == 0:
            return img_np, (0, 0)
        padded = np.pad(img_np, ((0, pad_h), (0, pad_w)), mode='edge')
        print(
            f"  Input size ({h}, {w}) is not divisible by {mult}; "
            f"padding to ({h + pad_h}, {w + pad_w}) for UNet compatibility."
        )
        return padded, (pad_h, pad_w)

    def restore_original_shape(self, array):
        """Crop an array back to the most recent original input shape."""
        if self._last_input_shape is None:
            return array
        h, w = self._last_input_shape
        arr = np.asarray(array)
        if arr.ndim == 2:
            return arr[:h, :w]
        if arr.ndim == 3:
            # (C, H, W)
            if arr.shape[1] >= h and arr.shape[2] >= w:
                return arr[:, :h, :w]
            # (H, W, C)
            if arr.shape[0] >= h and arr.shape[1] >= w:
                return arr[:h, :w, :]
        if arr.ndim == 4 and arr.shape[2] >= h and arr.shape[3] >= w:
            return arr[:, :, :h, :w]
        return arr

    def preprocess_image(self, img):
        """
        Preprocess input image

        Returns both:
        - Tensor in [-1, 1] for diffusion model
        - NumPy array in [0, 1] linear space for metrics/visualization
        """
        if isinstance(img, str):
            img = Image.open(img).convert('L')

        if isinstance(img, Image.Image):
            img_np = np.array(img).astype(np.float32) / 255.0
        elif isinstance(img, torch.Tensor):
            img_np = img.cpu().numpy()
        else:
            img_np = img.astype(np.float32)
            if img_np.max() > 1.0:
                img_np /= 255.0

        if img_np.ndim == 3:
            img_np = img_np.mean(axis=-1)

        self._last_input_original = np.array(img_np, copy=True)
        self._last_input_shape = tuple(img_np.shape)
        img_np, pad_hw = self._pad_to_model_compatible_size(img_np)
        self._last_model_shape = tuple(img_np.shape)
        self._last_input_padding = pad_hw

        # Tensor for diffusion ([-1, 1])
        img_tensor = torch.from_numpy(img_np).float().unsqueeze(0).unsqueeze(0).to(self.device)
        img_tensor = img_tensor * 2 - 1

        return img_tensor, img_np

    def wn_ddnm_sample_batch(self, y_noisy, batch_size, base_seed=42):
        """
        WN-DDNM Batch Sampling with Range-Null Space Decomposition (LINEAR SPACE)

        DDIM sampler only (deterministic).

        Args:
            y_noisy: Observation tensor [-1, 1], shape (1, 1, H, W)
            batch_size: Number of samples to generate in parallel
            base_seed: Base seed for reproducibility

        Returns:
            x: Denoised samples tensor, shape (batch_size, 1, H, W)
        """
        if self.sampler != 'ddim':
            raise ValueError(f"Unsupported sampler: {self.sampler}. Only 'ddim' is available.")
        return self._sample_ddim(y_noisy, batch_size, base_seed)

    def _prepare_range_null(self, y_noisy, batch_size):
        """Prepare range-space projection and intensity mask (shared by all samplers)

        Pixel weighting mask computed in the linear domain:
        - performs the actual B-mode to linear conversion
        - applies linear normalization plus a gamma to strengthen contrast
        """
        B, C, H, W = y_noisy.shape

        # Convert observation to [0, 1] (B-mode normalized)
        y_01 = (y_noisy + 1) / 2
        y_01 = torch.clamp(y_01, 0, 1)
        y_01_np = y_01.squeeze().cpu().numpy()

        # Intensity-adaptive soft mask from Linear domain
        if self.use_linear_range:
            intensity_mask = self.compute_linear_intensity_mask(y_01_np)

            print(f"  Linear weight mask (center={self.linear_mask_center:.2f}, "
                  f"gamma={self.linear_mask_steepness:.2f}, cap={self.max_intensity_cap:.2f}, "
                  f"otsu_strength={self.otsu_strength:.2f}): "
                  f"min={intensity_mask.min():.3f}, max={intensity_mask.max():.3f}, "
                  f"mean={intensity_mask.mean():.3f}")

            self._intensity_mask = intensity_mask
            self._intensity_weight = intensity_mask
            self._weight_mask = intensity_mask
            self._use_adaptive_mask = True
        else:
            self._use_adaptive_mask = False

        # Range-space projection, performed in the B-mode domain
        y_obs_range = self._range_projection_np(y_01_np)

        y_obs_range_tensor = torch.from_numpy(y_obs_range).unsqueeze(0).unsqueeze(0).float().to(self.device)
        y_obs_range_batch = y_obs_range_tensor.expand(batch_size, -1, -1, -1)
        y_noisy_batch = y_noisy.expand(batch_size, -1, -1, -1)

        return y_obs_range_batch, y_noisy_batch, H, W

    def _apply_range_null_decomposition(self, x_0_pred, y_obs_range_batch, batch_size):
        """Apply Range-Null decomposition to x0 prediction with intensity-adaptive weighting

        Pixel weighting driven by linear intensity:
        - bright tissue:    keep the range and null composition
        - dark background:  lean on x0_pred for stronger denoising
        """
        # Convert prediction to [0,1]
        x_0_pred_01 = (x_0_pred + 1) / 2
        x_0_pred_01 = torch.clamp(x_0_pred_01, 0, 1)

        # Compute null-space projection
        x_0_pred_01_np = x_0_pred_01.squeeze(1).cpu().numpy()
        x_0_null = np.stack([
            x_0_pred_01_np[b] - self._range_projection_np(x_0_pred_01_np[b])
            for b in range(batch_size)
        ])
        x_0_null = np.nan_to_num(x_0_null, nan=0.0)
        x_0_null_tensor = torch.from_numpy(x_0_null).unsqueeze(1).float().to(self.device)

        # Combine range and null space with intensity-adaptive weighting
        if hasattr(self, '_use_adaptive_mask') and self._use_adaptive_mask:
            # Continuous soft mask in [0, 1]
            mask_source = self._intensity_mask if self._intensity_mask is not None else self._weight_mask
            mask_tensor = torch.from_numpy(mask_source).unsqueeze(0).unsqueeze(0).float().to(self.device)
            mask_batch = mask_tensor.expand(batch_size, -1, -1, -1)

            range_null_combined = (self.range_weight * y_obs_range_batch +
                                  self.null_weight * x_0_null_tensor)
            x_0_bar_01 = mask_batch * range_null_combined + (1 - mask_batch) * x_0_pred_01
            x_0_bar_01 = torch.clamp(x_0_bar_01, 0, 1)
        else:
            # Non-adaptive path
            x_0_bar_01 = (self.range_weight * y_obs_range_batch +
                          self.null_weight * x_0_null_tensor)
            x_0_bar_01 = torch.clamp(x_0_bar_01, 0, 1)

        # Convert back to [-1, 1]
        x_0_bar = x_0_bar_01 * 2 - 1
        return x_0_bar

    def _predict_x0_from_noise(self, x, eps_pred, t):
        """Predict x0 from noise prediction"""
        sqrt_recip = self.sqrt_recip_alphas_cumprod[t].view(-1, 1, 1, 1)
        sqrt_recipm1 = self.sqrt_recipm1_alphas_cumprod[t].view(-1, 1, 1, 1)
        x_0_pred = sqrt_recip * x - sqrt_recipm1 * eps_pred
        return torch.clamp(x_0_pred, -1, 1)

    def _sample_ddim(self, y_noisy, batch_size, base_seed=42):
        """DDIM sampler with WN-DDNM Range-Null decomposition"""
        torch.manual_seed(base_seed)
        np.random.seed(base_seed)

        y_obs_range_batch, y_noisy_batch, H, W = self._prepare_range_null(y_noisy, batch_size)
        x = torch.randn(batch_size, 1, H, W, device=self.device)

        for i, t_curr in enumerate(tqdm(self.ddim_timesteps, desc="  WN-DDNM (DDIM)")):
            t_next = self.ddim_timesteps[i + 1] if i + 1 < len(self.ddim_timesteps) else -1
            lambda_t = self.compute_guidance_strength(t_curr)

            with torch.no_grad():
                t_tensor = torch.tensor([t_curr] * batch_size, device=self.device, dtype=torch.long)
                model_output = self.model(x, t_tensor)
                eps_pred = model_output[:, 0:1, :, :] if model_output.shape[1] == 2 else model_output

                x_0_pred = self._predict_x0_from_noise(x, eps_pred, t_curr)
                x_0_bar = self._apply_range_null_decomposition(x_0_pred, y_obs_range_batch, batch_size)
                x_0_hat = (1 - lambda_t * 0.3) * x_0_bar + lambda_t * 0.3 * y_noisy_batch

                if t_next >= 0:
                    alpha_bar_curr = self.alphas_cumprod[t_curr]
                    alpha_bar_next = self.alphas_cumprod[t_next]

                    if self.eta > 0:
                        sigma_t = self.eta * torch.sqrt(
                            (1 - alpha_bar_next) / (1 - alpha_bar_curr)
                        ) * torch.sqrt(1 - alpha_bar_curr / alpha_bar_next)
                        noise_coeff = torch.sqrt(1 - alpha_bar_next - sigma_t ** 2)
                        noise = torch.randn_like(x)
                        x = torch.sqrt(alpha_bar_next) * x_0_hat + noise_coeff * eps_pred + sigma_t * noise
                    else:
                        x = torch.sqrt(alpha_bar_next) * x_0_hat + torch.sqrt(1 - alpha_bar_next) * eps_pred
                else:
                    x = x_0_hat

        x_01 = (x + 1) / 2
        return torch.clamp(x_01, 0, 1)

    def generate_ensemble(self, y_noisy, base_seed=1000):
        """
        Generate ensemble of denoised samples using WN-DDNM

        Args:
            y_noisy: Observation tensor [-1, 1], shape (1, 1, H, W)
            base_seed: Seed assigned to the first sampling batch. Supplying a
                different value produces a non-overlapping ensemble while the
                default preserves the historical deterministic behavior.

        Returns:
            samples: NumPy array of shape (C, H, W) in [0, 1]
        """
        num_batches = (self.C + self.batch_size - 1) // self.batch_size

        if num_batches == 1:
            print(f"\nGenerating WN-DDNM ensemble (C={self.C}) with batch processing...")
        else:
            print(f"\nGenerating WN-DDNM ensemble (C={self.C}) in {num_batches} batches...")

        all_samples = []

        for batch_idx in range(num_batches):
            start_idx = batch_idx * self.batch_size
            end_idx = min(start_idx + self.batch_size, self.C)
            current_batch_size = end_idx - start_idx

            if num_batches > 1:
                print(f"\n  Batch {batch_idx + 1}/{num_batches} (samples {start_idx + 1}-{end_idx})...")

            # Different, reproducible seed for each batch.
            batch_seed = int(base_seed) + batch_idx * 10000

            # Run WN-DDNM batch sampling
            x_batch = self.wn_ddnm_sample_batch(y_noisy, current_batch_size, batch_seed)

            # Convert to numpy [0, 1]
            batch_samples = x_batch.squeeze(1).cpu().numpy()  # (B, H, W)
            all_samples.append(batch_samples)

            # Clear GPU cache between batches
            if num_batches > 1 and str(self.device).startswith('cuda'):
                torch.cuda.empty_cache()

        # Concatenate all batches
        samples = np.concatenate(all_samples, axis=0)  # (C, H, W)

        print(f"  WN-DDNM ensemble complete: {samples.shape}")
        return samples

    def compute_statistics(self, samples):
        """
        Compute ensemble statistics

        Returns:
            mean_img: Ensemble mean
            variance: Ensemble variance
            uncertainty: Normalized uncertainty map
        """
        C = samples.shape[0]
        mean_img = samples.mean(axis=0)
        if C > 1:
            # Paper Eq. 19 uses the population dispersion over the N samples.
            variance = ((samples - mean_img)**2).sum(axis=0) / C
            std_dev = np.sqrt(np.maximum(variance, 0.0))
            max_std = float(std_dev.max())
            uncertainty = (
                std_dev / (max_std + 1e-10)
                if max_std > 1e-10
                else np.zeros_like(std_dev)
            )
        else:
            # Single-sample inference has no ensemble variance; keep uncertainty at 0
            # so best-sample-aware fusion falls back to the sample itself without NaNs.
            variance = np.zeros_like(mean_img)
            uncertainty = np.zeros_like(mean_img)

        print(f"  Ensemble statistics:")
        print(f"    Mean intensity: {mean_img.mean():.4f}")
        print(f"    Uncertainty: mean={uncertainty.mean():.4f}, max={uncertainty.max():.4f}")

        return mean_img, variance, uncertainty

    def adaptive_fusion(self, samples, mean_img, uncertainty):
        """
        Adaptive fusion using uncertainty-weighted averaging

        High uncertainty regions → trust mean more (stronger denoising)
        Low uncertainty regions → preserve some texture
        """
        # Normalize uncertainty
        u_norm = (uncertainty - uncertainty.min()) / (uncertainty.max() - uncertainty.min() + 1e-10)

        # Weight: high uncertainty → high weight on mean
        weight = 0.7 + 0.28 * u_norm
        weight = np.clip(weight, 0.7, 0.98)

        # Use median as texture base (more robust than single sample)
        texture_base = np.median(samples, axis=0)

        # Blend
        final_img = weight * mean_img + (1 - weight) * texture_base
        final_img = np.clip(final_img, 0, 1)

        print(f"  Adaptive fusion:")
        print(f"    Weight range: [{weight.min():.3f}, {weight.max():.3f}]")

        return final_img, weight

    @staticmethod
    def _safe_minmax_norm(values):
        values = np.asarray(values, dtype=np.float32)
        vmin = float(np.min(values))
        vmax = float(np.max(values))
        if vmax <= vmin + 1e-10:
            return np.zeros_like(values, dtype=np.float32)
        return (values - vmin) / (vmax - vmin + 1e-10)

    @staticmethod
    def _otsu_threshold(x, bins=256):
        x = np.clip(np.asarray(x, dtype=np.float32), 0.0, 1.0)
        hist, bin_edges = np.histogram(x.ravel(), bins=bins, range=(0.0, 1.0))
        hist = hist.astype(np.float64)
        weight1 = np.cumsum(hist)
        weight2 = np.cumsum(hist[::-1])[::-1]
        bin_mids = 0.5 * (bin_edges[:-1] + bin_edges[1:])
        mean1 = np.cumsum(hist * bin_mids) / np.maximum(weight1, 1e-12)
        mean2 = (np.cumsum((hist * bin_mids)[::-1]) / np.maximum(weight2, 1e-12))[::-1]
        between = weight1[:-1] * weight2[1:] * (mean1[:-1] - mean2[1:]) ** 2
        if between.size == 0:
            return 0.5
        return float(bin_mids[int(np.argmax(between))])

    def score_sample_quality(self, sample, observation, mean_img):
        """
        Calculate raw per-sample quality components.

        Components:
        - SNR (mu/sigma)
        - Edge sharpness (average gradient magnitude)
        - gCNR-like separation (Otsu split of bright/dark regions)
        - NCC consistency with observation and ensemble mean
        """
        sample = np.asarray(sample, dtype=np.float32)
        observation = np.asarray(observation, dtype=np.float32)
        mean_img = np.asarray(mean_img, dtype=np.float32)
        eps = 1e-10

        snr_score = float(core_snr(sample))

        gy, gx = np.gradient(sample)
        edge_score = float(np.sqrt(gx * gx + gy * gy).mean())

        threshold = self._otsu_threshold(sample)
        bright_region = sample[sample >= threshold]
        dark_region = sample[sample < threshold]
        if bright_region.size > 10 and dark_region.size > 10:
            gcnr_score = float(core_gcnr(bright_region, dark_region))
        else:
            gcnr_score = 0.5

        ncc_obs = float(
            np.sum(sample * observation)
            / (np.linalg.norm(sample.ravel()) * np.linalg.norm(observation.ravel()) + eps)
        )
        ncc_mean = float(
            np.sum(sample * mean_img)
            / (np.linalg.norm(sample.ravel()) * np.linalg.norm(mean_img.ravel()) + eps)
        )
        ncc_score = 0.6 * ncc_obs + 0.4 * ncc_mean

        return {
            'snr': snr_score,
            'edge': edge_score,
            'gcnr': gcnr_score,
            'ncc': ncc_score,
            'ncc_obs': ncc_obs,
            'ncc_mean': ncc_mean,
        }

    def identify_best_sample(self, samples, observation, mean_img):
        """Identify best sample and compute soft quality weights."""
        quality_components = [
            self.score_sample_quality(sample, observation, mean_img)
            for sample in samples
        ]

        snr_values = np.array([item['snr'] for item in quality_components], dtype=np.float32)
        edge_values = np.array([item['edge'] for item in quality_components], dtype=np.float32)
        gcnr_values = np.array([item['gcnr'] for item in quality_components], dtype=np.float32)
        ncc_values = np.array([item['ncc'] for item in quality_components], dtype=np.float32)

        snr_norm = self._safe_minmax_norm(snr_values)
        edge_norm = self._safe_minmax_norm(edge_values)
        gcnr_norm = self._safe_minmax_norm(gcnr_values)
        if np.max(ncc_values) - np.min(ncc_values) < 1e-8:
            ncc_norm = np.clip((ncc_values + 1.0) * 0.5, 0.0, 1.0)
        else:
            ncc_norm = self._safe_minmax_norm(ncc_values)

        # Weighted aggregate score (gCNR-centric).
        scores = 0.35 * gcnr_norm + 0.25 * snr_norm + 0.25 * edge_norm + 0.15 * ncc_norm
        best_idx = int(np.argmax(scores))

        temperature = self.fusion_temperature
        exp_scores = np.exp((scores - np.max(scores)) / temperature)
        quality_weights = exp_scores / (np.sum(exp_scores) + 1e-12)

        normalized_components = {
            'snr_norm': snr_norm,
            'edge_norm': edge_norm,
            'gcnr_norm': gcnr_norm,
            'ncc_norm': ncc_norm,
        }
        raw_components = {
            'snr': snr_values,
            'edge': edge_values,
            'gcnr': gcnr_values,
            'ncc': ncc_values,
        }
        return best_idx, samples[best_idx], scores, quality_weights, raw_components, normalized_components

    def frequency_aware_fusion(self, mean_img, best_sample, uncertainty):
        """
        Frequency-domain fusion:
        LF from ensemble mean + HF from best sample.
        """
        mean_lf = self._range_projection_np(mean_img)
        best_hf = best_sample - self._range_projection_np(best_sample)
        base_fusion = np.clip(mean_lf + best_hf, 0, 1)

        u_norm = self._safe_minmax_norm(uncertainty)
        texture_weight = np.clip(1.0 - 0.5 * u_norm, 0.5, 1.0)

        final = texture_weight * base_fusion + (1.0 - texture_weight) * mean_img
        return np.clip(final, 0, 1), texture_weight

    def uncertainty_best_blend(self, mean_img, best_sample, uncertainty):
        """
        Low uncertainty -> preserve best sample texture.
        High uncertainty -> trust ensemble mean for stronger denoising.
        """
        u_norm = self._safe_minmax_norm(uncertainty)
        best_weight = 1.0 - np.sqrt(np.clip(u_norm, 0.0, 1.0))
        best_weight = np.clip(best_weight, 0.2, 0.95)
        final = best_weight * best_sample + (1.0 - best_weight) * mean_img
        return np.clip(final, 0, 1), best_weight

    def paper_fusion(self, mean_img, best_sample, uncertainty):
        """Implement the bounded convex fusion in paper Eq. 19 through Eq. 21.

        The returned map is the ensemble-mean weight W.  Uncertainty is scaled
        by its maximum, then W increases linearly from ``fusion_w_min`` to
        ``fusion_w_max``.
        """
        sigma = np.asarray(uncertainty, dtype=np.float32)
        u_norm = sigma / (float(np.max(sigma)) + 1e-10)
        u_norm = np.clip(u_norm, 0.0, 1.0)
        mean_weight = self.fusion_w_min + (
            self.fusion_w_max - self.fusion_w_min
        ) * u_norm
        mean_weight = np.clip(
            mean_weight, self.fusion_w_min, self.fusion_w_max
        )
        final = mean_weight * mean_img + (1.0 - mean_weight) * best_sample
        return np.clip(final, 0.0, 1.0), mean_weight

    def topk_weighted_fusion(self, samples, quality_weights, k=5):
        """Weighted fusion over top-k quality samples."""
        num_samples = samples.shape[0]
        k = int(max(1, min(k, num_samples)))
        top_indices = np.argsort(quality_weights)[-k:]
        top_weights = quality_weights[top_indices]
        top_weights = top_weights / (np.sum(top_weights) + 1e-12)
        fused = np.tensordot(top_weights, samples[top_indices], axes=(0, 0))
        return np.clip(fused, 0, 1), top_indices, top_weights

    def best_sample_aware_fusion(self, samples, observation, mean_img, uncertainty, fusion_strategy='paper'):
        """Wrapper for best-sample-aware fusion strategies."""
        (
            best_idx,
            best_sample,
            scores,
            quality_weights,
            raw_components,
            normalized_components,
        ) = self.identify_best_sample(samples, observation, mean_img)

        print(f"  Best sample: #{best_idx} (score: {scores[best_idx]:.4f})")
        print(f"  Score range: [{scores.min():.4f}, {scores.max():.4f}]")

        weight_map = None
        topk_indices = None
        topk_weights = None

        if fusion_strategy == 'paper':
            final_img, weight_map = self.paper_fusion(mean_img, best_sample, uncertainty)
        elif fusion_strategy == 'frequency':
            final_img, weight_map = self.frequency_aware_fusion(mean_img, best_sample, uncertainty)
        elif fusion_strategy == 'uncertainty_blend':
            final_img, weight_map = self.uncertainty_best_blend(mean_img, best_sample, uncertainty)
        elif fusion_strategy == 'topk':
            final_img, topk_indices, topk_weights = self.topk_weighted_fusion(
                samples, quality_weights, k=self.topk
            )
            # Scalar visualization map for top-k strategy.
            weight_map = np.full_like(mean_img, float(np.max(topk_weights)))
            print(
                f"  Top-K indices: {topk_indices.tolist()} "
                f"weights={np.round(topk_weights, 4).tolist()}"
            )
        else:
            raise ValueError(f"Unknown fusion strategy: {fusion_strategy}")

        return final_img, {
            'strategy': fusion_strategy,
            'best_idx': best_idx,
            'best_sample': best_sample,
            'scores': scores,
            'quality_weights': quality_weights,
            'weight_map': weight_map,
            'topk_indices': topk_indices,
            'topk_weights': topk_weights,
            'raw_components': raw_components,
            'normalized_components': normalized_components,
        }

    def denoise(self, input_image, base_seed=1000):
        """
        Full WN-DDNM denoising pipeline

        Args:
            input_image: Path to image or numpy array
            base_seed: Seed for the first batch of the diffusion ensemble.

        Returns:
            results: Dictionary with denoised image and statistics
        """
        print(f"\n{'='*60}")
        print(f"WN-DDNM Speckle Denoising Pipeline")
        print(f"{'='*60}")

        # Preprocess
        print("Step 1: Preprocessing...")
        y_noisy, original_model = self.preprocess_image(input_image)
        original = np.array(self._last_input_original, copy=True)
        print(f"  Input shape: {original.shape}")
        print(f"  Model shape: {original_model.shape}")
        print(f"  Input intensity: min={original.min():.4f}, max={original.max():.4f}")

        # Generate ensemble with WN-DDNM
        print(f"\nStep 2: WN-DDNM Ensemble Generation (C={self.C})...")
        samples = self.generate_ensemble(y_noisy, base_seed=base_seed)

        # Compute statistics
        print("\nStep 3: Computing ensemble statistics...")
        mean_img, variance, uncertainty = self.compute_statistics(samples)

        # Fusion
        fusion_info = None
        if self.use_best_sample_fusion:
            print(f"\nStep 4: Best-sample-aware fusion ({self.fusion_strategy})...")
            final_img, fusion_info = self.best_sample_aware_fusion(
                samples,
                original_model,
                mean_img,
                uncertainty,
                fusion_strategy=self.fusion_strategy,
            )
            weight = fusion_info.get('weight_map')
            if weight is None:
                weight = np.ones_like(mean_img, dtype=np.float32)
        else:
            print("\nStep 4: Adaptive fusion...")
            final_img, weight = self.adaptive_fusion(samples, mean_img, uncertainty)

        # Restore outputs back to original input shape if model padding was applied.
        samples = self.restore_original_shape(samples)
        mean_img = self.restore_original_shape(mean_img)
        variance = self.restore_original_shape(variance)
        uncertainty = self.restore_original_shape(uncertainty)
        final_img = self.restore_original_shape(final_img)
        weight = self.restore_original_shape(weight)
        if fusion_info is not None:
            if fusion_info.get('best_sample') is not None:
                fusion_info['best_sample'] = self.restore_original_shape(fusion_info['best_sample'])
            if fusion_info.get('weight_map') is not None:
                fusion_info['weight_map'] = self.restore_original_shape(fusion_info['weight_map'])

        # Compute metrics
        print("\nStep 5: Computing metrics...")
        diff = np.abs(original - final_img)
        mse = ((original - final_img)**2).mean()
        psnr = 10 * np.log10(1.0 / mse) if mse > 0 else float('inf')

        print(f"  MSE: {mse:.8f}")
        print(f"  PSNR: {psnr:.2f} dB")
        print(f"  Mean abs diff: {diff.mean():.6f}")

        results = {
            'denoised': final_img,
            'mean': mean_img,
            'variance': variance,
            'uncertainty': uncertainty,
            'weight': weight,
            'samples': samples,
            'original': original,
            'fusion_info': fusion_info,
            'best_sample_idx': None if fusion_info is None else fusion_info.get('best_idx'),
            'quality_scores': None if fusion_info is None else fusion_info.get('scores'),
            'metrics': {
                'mse': mse,
                'psnr': psnr,
                'mean_diff': diff.mean(),
                'max_diff': diff.max()
            }
        }

        print(f"\n{'='*60}")
        print(f"WN-DDNM Denoising complete!")
        print(f"{'='*60}\n")

        return results

    def visualize_results(self, results, save_path=None):
        """Visualize WN-DDNM denoising results"""
        fig, axes = plt.subplots(2, 4, figsize=(16, 8))

        # Row 1: Main results
        axes[0, 0].imshow(results['original'], cmap='gray', vmin=0, vmax=1)
        axes[0, 0].set_title('Original (Speckle)')
        axes[0, 0].axis('off')

        axes[0, 1].imshow(results['mean'], cmap='gray', vmin=0, vmax=1)
        axes[0, 1].set_title(f'WN-DDNM Mean (C={self.C})')
        axes[0, 1].axis('off')

        axes[0, 2].imshow(results['denoised'], cmap='gray', vmin=0, vmax=1)
        axes[0, 2].set_title(f"WN-DDNM Output\nPSNR={results['metrics']['psnr']:.1f}dB")
        axes[0, 2].axis('off')

        diff = np.abs(results['original'] - results['denoised'])
        im0 = axes[0, 3].imshow(diff, cmap='hot', vmin=0, vmax=0.3)
        axes[0, 3].set_title('Absolute Difference')
        axes[0, 3].axis('off')
        plt.colorbar(im0, ax=axes[0, 3], fraction=0.046)

        # Row 2: Statistics
        im1 = axes[1, 0].imshow(results['uncertainty'], cmap='jet', vmin=0, vmax=1)
        axes[1, 0].set_title('Uncertainty Map')
        axes[1, 0].axis('off')
        plt.colorbar(im1, ax=axes[1, 0], fraction=0.046)

        im2 = axes[1, 1].imshow(results['variance'], cmap='viridis')
        axes[1, 1].set_title('Variance Map')
        axes[1, 1].axis('off')
        plt.colorbar(im2, ax=axes[1, 1], fraction=0.046)

        fusion_info = results.get('fusion_info') or {}
        weight_map = results.get('weight')
        if weight_map is None:
            weight_map = np.ones_like(results['denoised'], dtype=np.float32)
        wmin = float(np.min(weight_map))
        wmax = float(np.max(weight_map))
        if np.isclose(wmin, wmax):
            wmin = max(0.0, wmin - 0.05)
            wmax = min(1.0, wmax + 0.05)
        im3 = axes[1, 2].imshow(weight_map, cmap='RdYlGn_r', vmin=wmin, vmax=wmax)
        fusion_name = fusion_info.get('strategy', 'adaptive')
        axes[1, 2].set_title(f'Fusion Weight ({fusion_name})')
        axes[1, 2].axis('off')
        plt.colorbar(im3, ax=axes[1, 2], fraction=0.046)

        # Sample visualization
        axes[1, 3].imshow(results['samples'][0], cmap='gray', vmin=0, vmax=1)
        axes[1, 3].set_title('Sample #1')
        axes[1, 3].axis('off')
        plt.suptitle('WN-DDNM: Wavelet-based Null-space Range-Null Decomposition',
                     fontsize=14, fontweight='bold')
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=150, bbox_inches='tight')
            print(f"Saved visualization: {save_path}")

        return fig


# ============================================================
# Main Function
# ============================================================

def main():
    preset_parser = argparse.ArgumentParser(add_help=False)
    preset_parser.add_argument('--preset', choices=sorted(PRESET_FILES), default='paper')
    selected_preset, _ = preset_parser.parse_known_args()

    parser = argparse.ArgumentParser(description="WN-DDNM Speckle Denoising")
    parser.add_argument(
        '--preset', choices=sorted(PRESET_FILES), default=selected_preset.preset,
        help='Named YAML preset. Explicit command-line options override it.',
    )
    parser.add_argument('--input', type=str, required=True,
                        help='Input speckle image or directory')
    parser.add_argument(
        '--checkpoint',
        type=str,
        default=os.environ.get(
            'UGNS_CHECKPOINT', str(paths.CHECKPOINT_DIR / 'ugns_prior.pt')
        ),
        help='Model checkpoint'
    )
    parser.add_argument(
        '--config',
        type=str,
        default=os.environ.get(
            'UGNS_CONFIG', str(paths.CHECKPOINT_DIR / 'config.json')
        ),
        help='Model config'
    )
    parser.add_argument('--output_dir', type=str, default='./wn_ddnm_output',
                        help='Output directory')
    parser.add_argument('--ensemble_size', type=int, default=10,
                        help='Ensemble size')
    parser.add_argument('--batch_size', type=int, default=10,
                        help='Pinned to N=10 by the paper preset. Reducing it changes '
                             'the sampled ensemble because chunks use different seeds.')
    parser.add_argument('--ddim_steps', type=int, default=100,
                        help='DDIM steps')
    parser.add_argument('--guidance_start', type=float, default=0.3,
                        help='Initial guidance strength')
    parser.add_argument('--guidance_end', type=float, default=0.0,
                        help='Final guidance strength')
    parser.add_argument('--guidance_power', type=float, default=2.0,
                        help='Guidance decay exponent; inert for the default cosine schedule')
    parser.add_argument('--lpf_mode', type=str, default='wavelet',
                        choices=['wavelet', 'avgpool'],
                        help='LPF operator mode')
    parser.add_argument('--lpf_kernel_size', type=int, default=3,
                        help='Kernel size for avgpool LPF mode')
    parser.add_argument('--lpf_wavelet', type=str, default='sym4',
                        help='Wavelet family for wavelet LPF mode')
    parser.add_argument('--lpf_level', type=int, default=3,
                        help='Decomposition level for wavelet LPF')
    parser.add_argument('--use_wavelet', action='store_true', default=True,
                        help='Enable wavelet/LPF range projection')
    parser.add_argument('--no_wavelet', action='store_false', dest='use_wavelet',
                        help='Disable wavelet/LPF (range projection uses raw input)')
    parser.add_argument('--use_srad', action='store_true', default=True,
                        help='Enable SRAD pre-filtering for range projection')
    parser.add_argument('--no_srad', action='store_false', dest='use_srad',
                        help='Disable SRAD pre-filtering')
    parser.add_argument('--srad_iterations', type=int, default=15,
                        help='SRAD iterations')
    parser.add_argument('--srad_q0', type=float, default=0.4,
                        help='SRAD q0 parameter (<=0 uses auto estimate)')
    parser.add_argument('--srad_delta_t', type=float, default=0.25,
                        help='SRAD time step (0 < dt <= 0.25)')
    parser.add_argument('--range_weight', type=float, default=1.0,
                        help='Weight for range-space (observation) preservation')
    parser.add_argument('--null_weight', type=float, default=1.0,
                        help='Weight for null-space (diffusion) regeneration')

    # === NEW: Advanced Sampling Options ===
    parser.add_argument('--timestep_schedule', type=str, default='karras',
                        choices=['uniform', 'karras', 'exponential', 'quadratic'],
                        help='Timestep spacing schedule: uniform (standard), karras (better at low steps), '
                             'exponential (large early, small late), quadratic (smooth)')
    parser.add_argument('--eta', type=float, default=0.0,
                        help='DDIM stochasticity: 0=deterministic, 0.3-0.5=some diversity, 1.0=DDPM-like')
    parser.add_argument('--guidance_schedule', type=str, default='cosine',
                        choices=['power', 'cosine', 'linear'],
                        help='Guidance strength decay schedule: cosine (default), power, linear')

    # === Linear Domain Intensity-Adaptive Options ===
    parser.add_argument('--use_linear_range', action='store_true', default=True,
                        help='Enable Linear domain intensity-adaptive denoising with soft mask')
    parser.add_argument('--db_range', type=float, default=60,
                        help='dB dynamic range for B-mode to Linear conversion (default: 60)')
    parser.add_argument('--use_otsu_gate', action='store_true', default=True,
                        help='Enable Otsu-based soft background gate (default)')
    parser.add_argument('--no_otsu_gate', action='store_false', dest='use_otsu_gate',
                        help='Disable Otsu-based soft background gate')
    parser.add_argument('--linear_mask_center', type=float, default=0.4,
                        help='Sigmoid center for intensity mask (0-1, default: 0.4). '
                         'Lower value = more regions treated as tissue')
    parser.add_argument('--linear_mask_steepness', type=float, default=3.5,
                        help='Gamma power for soft mask (default: 3.5, range: 2.0-6.0). '
                             'Lower=smoother/artifact-free, Higher=sharper. '
                             'WARNING: Values >6.0 may cause white point artifacts.')
    parser.add_argument('--max_intensity_cap', type=float, default=0.92,
                        help='Upper bound for intensity mask values (default: 0.92). '
                             'Lower values reduce white saturation artifacts.')
    parser.add_argument('--otsu_strength', type=float, default=0.7,
                        help='Blend strength of Otsu gate in [0,1] (default: 0.7). '
                             '0 disables gate effect, 1 applies full gate.')
    parser.add_argument('--use_best_sample_fusion', action='store_true', default=True,
                        help='Enable best-sample-aware fusion (default: enabled)')
    parser.add_argument('--no_best_sample_fusion', action='store_false', dest='use_best_sample_fusion',
                        help='Disable best-sample-aware fusion and use adaptive fusion')
    parser.add_argument('--fusion_strategy', type=str, default='paper',
                        choices=['paper', 'frequency', 'uncertainty_blend', 'topk'],
                        help='Best-sample fusion strategy')
    parser.add_argument('--fusion_w_min', type=float, default=0.7,
                        help='Minimum ensemble-mean weight for paper fusion')
    parser.add_argument('--fusion_w_max', type=float, default=0.98,
                        help='Maximum ensemble-mean weight for paper fusion')
    parser.add_argument('--topk', type=int, default=5,
                        help='Top-k samples; inert unless --fusion_strategy topk')
    parser.add_argument('--fusion_temperature', type=float, default=0.3,
                        help='Softmax temperature; inert unless --fusion_strategy topk')

    # Sampler selection (DDIM only)
    parser.add_argument('--sampler', type=str, default='ddim',
                        choices=['ddim'],
                        help='Sampler: ddim')
    parser.add_argument('--device', type=str,
                        default='cuda' if torch.cuda.is_available() else 'cpu')
    parser.add_argument('--model_name', type=str, default='wn_ddnm',
                        help='Model name for output organization')

    preset_defaults = load_preset_defaults(selected_preset.preset)
    valid_destinations = {action.dest for action in parser._actions}
    unknown_keys = sorted(set(preset_defaults) - valid_destinations)
    if unknown_keys:
        parser.error(f"Unknown keys in {PRESET_FILES[selected_preset.preset]}: {unknown_keys}")
    parser.set_defaults(**preset_defaults)
    args = parser.parse_args()

    configure_cuda_runtime(args.device, args.batch_size)

    # Create output directories
    os.makedirs(args.output_dir, exist_ok=True)
    model_output_dir = os.path.join(args.output_dir, args.model_name)
    os.makedirs(model_output_dir, exist_ok=True)

    # Create denoiser
    denoiser = WNDDNMDenoiser(
        checkpoint_path=args.checkpoint,
        config_path=args.config,
        device=args.device,
        ensemble_size=args.ensemble_size,
        batch_size=args.batch_size,
        ddim_steps=args.ddim_steps,
        guidance_start=args.guidance_start,
        guidance_end=args.guidance_end,
        guidance_power=args.guidance_power,
        lpf_mode=args.lpf_mode,
        lpf_kernel_size=args.lpf_kernel_size,
        lpf_wavelet=args.lpf_wavelet,
        lpf_level=args.lpf_level,
        range_weight=args.range_weight,
        null_weight=args.null_weight,
        timestep_schedule=args.timestep_schedule,
        eta=args.eta,
        guidance_schedule=args.guidance_schedule,
        use_linear_range=args.use_linear_range,
        db_range=args.db_range,
        use_otsu_gate=args.use_otsu_gate,
        sampler=args.sampler,
        linear_mask_center=args.linear_mask_center,
        linear_mask_steepness=args.linear_mask_steepness,
        max_intensity_cap=args.max_intensity_cap,
        otsu_strength=args.otsu_strength,
        use_wavelet=args.use_wavelet,
        use_srad=args.use_srad,
        srad_iterations=args.srad_iterations,
        srad_q0=args.srad_q0,
        srad_delta_t=args.srad_delta_t,
        use_best_sample_fusion=args.use_best_sample_fusion,
        fusion_strategy=args.fusion_strategy,
        fusion_w_min=args.fusion_w_min,
        fusion_w_max=args.fusion_w_max,
        topk=args.topk,
        fusion_temperature=args.fusion_temperature,
    )

    # Check if input is directory or single file
    if os.path.isdir(args.input):
        print(f"\n{'='*60}")
        print(f"Processing directory: {args.input}")
        print(f"{'='*60}\n")

        image_extensions = ['.png', '.jpg', '.jpeg', '.bmp', '.tif', '.tiff']
        image_files = []
        for ext in image_extensions:
            image_files.extend(sorted([f for f in os.listdir(args.input)
                                      if f.lower().endswith(ext)]))

        if not image_files:
            print(f"No image files found in {args.input}")
            return

        print(f"Found {len(image_files)} images to process\n")

        for idx, img_name in enumerate(image_files, 1):
            img_path = os.path.join(args.input, img_name)
            print(f"\n{'='*60}")
            print(f"Processing [{idx}/{len(image_files)}]: {img_name}")
            print(f"{'='*60}\n")

            try:
                basename = os.path.splitext(img_name)[0]

                # Run denoising
                results = denoiser.denoise(img_path)

                # Save denoised image
                denoised_path = os.path.join(model_output_dir, f'{basename}_denoised.png')
                Image.fromarray((results['denoised'] * 255).astype(np.uint8)).save(denoised_path)
                print(f"Saved: {denoised_path}")

                # Save uncertainty map
                uncertainty_path = os.path.join(model_output_dir, f'{basename}_uncertainty.png')
                Image.fromarray((results['uncertainty'] * 255).astype(np.uint8)).save(uncertainty_path)
                print(f"Saved: {uncertainty_path}")

                # Save visualization
                viz_path = os.path.join(model_output_dir, f'{basename}_visualization.png')
                denoiser.visualize_results(results, save_path=viz_path)
                plt.close('all')

            except Exception as e:
                print(f"Error processing {img_name}: {str(e)}")
                import traceback
                traceback.print_exc()
                continue

        print(f"\n{'='*60}")
        print(f"All results saved to: {model_output_dir}")
        print(f"{'='*60}\n")

    else:
        # Process single image
        basename = os.path.splitext(os.path.basename(args.input))[0]

        # Run denoising
        results = denoiser.denoise(args.input)

        # Save denoised image
        denoised_path = os.path.join(model_output_dir, f'{basename}_denoised.png')
        Image.fromarray((results['denoised'] * 255).astype(np.uint8)).save(denoised_path)
        print(f"Saved: {denoised_path}")

        # Save uncertainty map
        uncertainty_path = os.path.join(model_output_dir, f'{basename}_uncertainty.png')
        Image.fromarray((results['uncertainty'] * 255).astype(np.uint8)).save(uncertainty_path)
        print(f"Saved: {uncertainty_path}")

        # Save visualization
        viz_path = os.path.join(model_output_dir, f'{basename}_visualization.png')
        denoiser.visualize_results(results, save_path=viz_path)

        print(f"\nAll results saved to: {model_output_dir}")


if __name__ == '__main__':
    main()
